name: Build Release Packages

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller anthropic email-validator flask flask-sqlalchemy gunicorn psutil requests python-dotenv
      - name: Build package
        run: python build.py
      - name: Create release package
        run: python create_release.py
      - name: Upload release package
        uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: releases/*.zip
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller anthropic email-validator flask flask-sqlalchemy gunicorn psutil requests python-dotenv
      - name: Build package
        run: python build.py
      - name: Create release package
        run: python create_release.py
      - name: Upload release package
        uses: actions/upload-artifact@v3
        with:
          name: macos-package
          path: releases/*.zip
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller anthropic email-validator flask flask-sqlalchemy gunicorn psutil requests python-dotenv
      - name: Build package
        run: python build.py
      - name: Create release package
        run: python create_release.py
      - name: Upload release package
        uses: actions/upload-artifact@v3
        with:
          name: linux-package
          path: releases/*.zip
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*.zip